use_frameworks!

platform :ios, '9.0'

target 'LYKHttpManger_Example' do
  pod 'LYKHttpManger', :path => '../'
  pod 'AFNetworking'
  pod 'YYKit'

  target 'LYKHttpManger_Tests' do
    inherit! :search_paths

    
  end
end
